<?php

namespace Database\Seeders;

use App\Models\ItemType;
use App\Models\SupplyProfile;
use Illuminate\Database\Seeder;

class PetGoodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create Pet-specific Item Types
        $petItemTypes = [
            ['name' => 'Dog Supplies', 'description' => 'Products specifically for dogs'],
            ['name' => 'Cat Supplies', 'description' => 'Products specifically for cats'],
            ['name' => 'Fish Supplies', 'description' => 'Products for aquarium and fish care'],
            ['name' => 'Small Animal Supplies', 'description' => 'Products for hamsters, guinea pigs, rabbits, etc.'],
            ['name' => 'Reptile Supplies', 'description' => 'Products for reptiles and amphibians'],
            ['name' => 'Pet Food', 'description' => 'Various types of pet food and treats'],
            ['name' => 'Pet Toys', 'description' => 'Toys and entertainment items for pets'],
            ['name' => 'Pet Health', 'description' => 'Health and wellness products for pets'],
            ['name' => 'Pet Grooming', 'description' => 'Grooming and hygiene products'],
            ['name' => 'Pet Accessories', 'description' => 'Collars, leashes, beds, and other accessories'],
        ];

        foreach ($petItemTypes as $itemType) {
            ItemType::updateOrCreate(
                ['name' => $itemType['name']],
                $itemType
            );
        }


        // Create Pet Supply Profiles
        $petSupplies = [
            // Dog Supplies
            [
                'supply_sku' => 'DOG-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Premium Dog Food - Chicken & Rice (5kg)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 10,
                'supply_price1' => 25.99,
                'supply_price2' => 23.99,
                'supply_price3' => 21.99,
                'unit_cost' => 18.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'DOG-TOY-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Durable Chew Toy - Large Size',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 5,
                'supply_price1' => 12.99,
                'supply_price2' => 11.99,
                'supply_price3' => 10.99,
                'unit_cost' => 7.50,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'DOG-COLLAR-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Adjustable Dog Collar - Leather',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 18.99,
                'supply_price2' => 17.99,
                'supply_price3' => 16.99,
                'unit_cost' => 12.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'DOG-SHAMPOO-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Dog Shampoo - Hypoallergenic (500ml)',
                'supply_qty' => 0,
                'supply_uom' => 'bottle',
                'supply_min_qty' => 8,
                'supply_price1' => 8.99,
                'supply_price2' => 7.99,
                'supply_price3' => 6.99,
                'unit_cost' => 4.50,
                'low_stock_threshold_percentage' => 25,
            ],

            // Cat Supplies
            [
                'supply_sku' => 'CAT-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Premium Cat Food - Salmon (2kg)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 12,
                'supply_price1' => 15.99,
                'supply_price2' => 14.99,
                'supply_price3' => 13.99,
                'unit_cost' => 10.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'CAT-TOY-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Interactive Cat Toy - Feather Wand',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 5,
                'supply_price1' => 9.99,
                'supply_price2' => 8.99,
                'supply_price3' => 7.99,
                'unit_cost' => 5.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'CAT-LITTER-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Clumping Cat Litter - Unscented (10kg)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 15,
                'supply_price1' => 12.99,
                'supply_price2' => 11.99,
                'supply_price3' => 10.99,
                'unit_cost' => 7.50,
                'low_stock_threshold_percentage' => 30,
            ],
            [
                'supply_sku' => 'CAT-SCRATCH-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Cat Scratching Post - Sisal Rope',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 24.99,
                'supply_price2' => 22.99,
                'supply_price3' => 20.99,
                'unit_cost' => 15.00,
                'low_stock_threshold_percentage' => 10,
            ],

            // Fish Supplies
            [
                'supply_sku' => 'FISH-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Tropical Fish Flakes (50g)',
                'supply_qty' => 0,
                'supply_uom' => 'bottle',
                'supply_min_qty' => 20,
                'supply_price1' => 6.99,
                'supply_price2' => 5.99,
                'supply_price3' => 4.99,
                'unit_cost' => 3.00,
                'low_stock_threshold_percentage' => 25,
            ],
            [
                'supply_sku' => 'FISH-TANK-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Glass Aquarium - 20 Gallon',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 1,
                'supply_price1' => 89.99,
                'supply_price2' => 79.99,
                'supply_price3' => 69.99,
                'unit_cost' => 50.00,
                'low_stock_threshold_percentage' => 5,
            ],
            [
                'supply_sku' => 'FISH-FILTER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Aquarium Filter - Power Filter',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 34.99,
                'supply_price2' => 29.99,
                'supply_price3' => 24.99,
                'unit_cost' => 18.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'FISH-DECOR-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Aquarium Decorations - Coral Reef Set',
                'supply_qty' => 0,
                'supply_uom' => 'set',
                'supply_min_qty' => 5,
                'supply_price1' => 19.99,
                'supply_price2' => 17.99,
                'supply_price3' => 15.99,
                'unit_cost' => 10.00,
                'low_stock_threshold_percentage' => 15,
            ],

            // Small Animal Supplies
            [
                'supply_sku' => 'HAMSTER-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Hamster Food Mix - Seeds & Pellets (500g)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 11,
                'supply_price1' => 8.99,
                'supply_price2' => 7.99,
                'supply_price3' => 6.99,
                'unit_cost' => 4.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'HAMSTER-CAGE-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Hamster Cage - Multi-level with Accessories',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 49.99,
                'supply_price2' => 44.99,
                'supply_price3' => 39.99,
                'unit_cost' => 28.00,
                'low_stock_threshold_percentage' => 8,
            ],
            [
                'supply_sku' => 'RABBIT-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Rabbit Food - Timothy Hay (1kg)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 10,
                'supply_price1' => 11.99,
                'supply_price2' => 10.99,
                'supply_price3' => 9.99,
                'unit_cost' => 6.50,
                'low_stock_threshold_percentage' => 25,
            ],
            [
                'supply_sku' => 'GUINEA-PIG-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Guinea Pig Hideout - Wooden House',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 16.99,
                'supply_price2' => 14.99,
                'supply_price3' => 12.99,
                'unit_cost' => 8.50,
                'low_stock_threshold_percentage' => 12,
            ],

            // Reptile Supplies
            [
                'supply_sku' => 'REPTILE-FOOD-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Live Crickets - Small (100 count)',
                'supply_qty' => 0,
                'supply_uom' => 'container',
                'supply_min_qty' => 10,
                'supply_price1' => 7.99,
                'supply_price2' => 6.99,
                'supply_price3' => 5.99,
                'unit_cost' => 3.50,
                'low_stock_threshold_percentage' => 30,
            ],
            [
                'supply_sku' => 'REPTILE-TANK-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Reptile Terrarium - 40 Gallon',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 1,
                'supply_price1' => 129.99,
                'supply_price2' => 119.99,
                'supply_price3' => 109.99,
                'unit_cost' => 75.00,
                'low_stock_threshold_percentage' => 5,
            ],
            [
                'supply_sku' => 'REPTILE-HEAT-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Reptile Heat Lamp - 100W',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 4,
                'supply_price1' => 22.99,
                'supply_price2' => 19.99,
                'supply_price3' => 16.99,
                'unit_cost' => 12.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'REPTILE-SUBSTRATE-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Reptile Substrate - Coconut Fiber (10L)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 6,
                'supply_price1' => 14.99,
                'supply_price2' => 13.99,
                'supply_price3' => 12.99,
                'unit_cost' => 8.00,
                'low_stock_threshold_percentage' => 20,
            ],

            // Pet Health & Grooming
            [
                'supply_sku' => 'PET-VITAMIN-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Pet Multivitamin - Chewable Tablets (60 count)',
                'supply_qty' => 0,
                'supply_uom' => 'bottle',
                'supply_min_qty' => 9,
                'supply_price1' => 18.99,
                'supply_price2' => 16.99,
                'supply_price3' => 14.99,
                'unit_cost' => 10.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'PET-BRUSH-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Pet Grooming Brush - Slicker Brush',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 6,
                'supply_price1' => 15.99,
                'supply_price2' => 13.99,
                'supply_price3' => 11.99,
                'unit_cost' => 7.50,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'PET-BED-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Pet Bed - Memory Foam (Medium)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 39.99,
                'supply_price2' => 34.99,
                'supply_price3' => 29.99,
                'unit_cost' => 22.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'PET-CARRIER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Pet Carrier - Soft-sided (Medium)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 29.99,
                'supply_price2' => 26.99,
                'supply_price3' => 23.99,
                'unit_cost' => 16.50,
                'low_stock_threshold_percentage' => 8,
            ],

            // Additional Pet Accessories
            [
                'supply_sku' => 'DOG-LEASH-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Retractable Dog Leash - 16ft (Medium)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 4,
                'supply_price1' => 24.99,
                'supply_price2' => 22.99,
                'supply_price3' => 20.99,
                'unit_cost' => 14.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'DOG-HARNESS-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Adjustable Dog Harness - No-Pull Design',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 19.99,
                'supply_price2' => 17.99,
                'supply_price3' => 15.99,
                'unit_cost' => 11.00,
                'low_stock_threshold_percentage' => 12,
            ],
            [
                'supply_sku' => 'DOG-BOWL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Stainless Steel Dog Bowl Set - 2 Bowls',
                'supply_qty' => 0,
                'supply_uom' => 'set',
                'supply_min_qty' => 5,
                'supply_price1' => 14.99,
                'supply_price2' => 12.99,
                'supply_price3' => 10.99,
                'unit_cost' => 7.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'DOG-CRATE-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Wire Dog Crate - Large (42 inch)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 89.99,
                'supply_price2' => 79.99,
                'supply_price3' => 69.99,
                'unit_cost' => 55.00,
                'low_stock_threshold_percentage' => 8,
            ],
            [
                'supply_sku' => 'DOG-GATE-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Pet Safety Gate - Extendable (28-42 inch)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 34.99,
                'supply_price2' => 29.99,
                'supply_price3' => 24.99,
                'unit_cost' => 18.00,
                'low_stock_threshold_percentage' => 10,
            ],

            // Cat Accessories
            [
                'supply_sku' => 'CAT-TREE-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Cat Tree - Multi-level with Condo',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 1,
                'supply_price1' => 79.99,
                'supply_price2' => 69.99,
                'supply_price3' => 59.99,
                'unit_cost' => 45.00,
                'low_stock_threshold_percentage' => 5,
            ],
            [
                'supply_sku' => 'CAT-BOWL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Ceramic Cat Bowl Set - Elevated Design',
                'supply_qty' => 0,
                'supply_uom' => 'set',
                'supply_min_qty' => 4,
                'supply_price1' => 18.99,
                'supply_price2' => 16.99,
                'supply_price3' => 14.99,
                'unit_cost' => 9.50,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'CAT-WINDOW-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Cat Window Perch - Suction Cup Mount',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 22.99,
                'supply_price2' => 19.99,
                'supply_price3' => 16.99,
                'unit_cost' => 12.00,
                'low_stock_threshold_percentage' => 12,
            ],
            [
                'supply_sku' => 'CAT-LITTER-BOX-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Covered Cat Litter Box - Large Size',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 32.99,
                'supply_price2' => 28.99,
                'supply_price3' => 24.99,
                'unit_cost' => 18.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'CAT-CARRIER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Hard-sided Cat Carrier - Airline Approved',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 2,
                'supply_price1' => 39.99,
                'supply_price2' => 34.99,
                'supply_price3' => 29.99,
                'unit_cost' => 22.00,
                'low_stock_threshold_percentage' => 8,
            ],

            // Fish Accessories
            [
                'supply_sku' => 'FISH-HEATER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Aquarium Heater - 100W with Thermostat',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 5,
                'supply_price1' => 28.99,
                'supply_price2' => 24.99,
                'supply_price3' => 20.99,
                'unit_cost' => 15.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'FISH-LIGHT-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'LED Aquarium Light - 24 inch',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 44.99,
                'supply_price2' => 39.99,
                'supply_price3' => 34.99,
                'unit_cost' => 25.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'FISH-NET-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Aquarium Fish Net - Fine Mesh (Small)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 8,
                'supply_price1' => 8.99,
                'supply_price2' => 7.99,
                'supply_price3' => 6.99,
                'unit_cost' => 4.50,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'FISH-GRAVEL-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Aquarium Gravel - Natural River Rock (5kg)',
                'supply_qty' => 0,
                'supply_uom' => 'bag',
                'supply_min_qty' => 5,
                'supply_price1' => 16.99,
                'supply_price2' => 14.99,
                'supply_price3' => 12.99,
                'unit_cost' => 8.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'FISH-TEST-KIT-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Water Test Kit - pH, Ammonia, Nitrite, Nitrate',
                'supply_qty' => 0,
                'supply_uom' => 'kit',
                'supply_min_qty' => 3,
                'supply_price1' => 24.99,
                'supply_price2' => 21.99,
                'supply_price3' => 18.99,
                'unit_cost' => 12.00,
                'low_stock_threshold_percentage' => 12,
            ],

            // Small Animal Accessories
            [
                'supply_sku' => 'HAMSTER-WHEEL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Silent Hamster Wheel - 8 inch',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 5,
                'supply_price1' => 12.99,
                'supply_price2' => 10.99,
                'supply_price3' => 8.99,
                'unit_cost' => 6.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'RABBIT-HUTCH-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Outdoor Rabbit Hutch - 2-story Design',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 1,
                'supply_price1' => 149.99,
                'supply_price2' => 129.99,
                'supply_price3' => 109.99,
                'unit_cost' => 80.00,
                'low_stock_threshold_percentage' => 3,
            ],
            [
                'supply_sku' => 'GUINEA-PIG-TUNNEL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Guinea Pig Tunnel Set - 3 Tunnels',
                'supply_qty' => 0,
                'supply_uom' => 'set',
                'supply_min_qty' => 4,
                'supply_price1' => 19.99,
                'supply_price2' => 17.99,
                'supply_price3' => 15.99,
                'unit_cost' => 10.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'SMALL-ANIMAL-BOWL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Ceramic Small Animal Bowl - Heavy Base',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 6,
                'supply_price1' => 9.99,
                'supply_price2' => 8.99,
                'supply_price3' => 7.99,
                'unit_cost' => 5.00,
                'low_stock_threshold_percentage' => 18,
            ],

            // Reptile Accessories
            [
                'supply_sku' => 'REPTILE-UVB-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'UVB Light Bulb - 10.0 (26W)',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 4,
                'supply_price1' => 18.99,
                'supply_price2' => 16.99,
                'supply_price3' => 14.99,
                'unit_cost' => 10.00,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'REPTILE-HIDE-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Reptile Hide Box - Natural Rock Design',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 3,
                'supply_price1' => 14.99,
                'supply_price2' => 12.99,
                'supply_price3' => 10.99,
                'unit_cost' => 7.00,
                'low_stock_threshold_percentage' => 12,
            ],
            [
                'supply_sku' => 'REPTILE-THERMOMETER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Digital Reptile Thermometer - Dual Probe',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 5,
                'supply_price1' => 16.99,
                'supply_price2' => 14.99,
                'supply_price3' => 12.99,
                'unit_cost' => 8.50,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'REPTILE-WATER-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Reptile Water Dish - Large Shallow Bowl',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 4,
                'supply_price1' => 11.99,
                'supply_price2' => 9.99,
                'supply_price3' => 7.99,
                'unit_cost' => 5.50,
                'low_stock_threshold_percentage' => 15,
            ],

            // General Pet Accessories
            [
                'supply_sku' => 'PET-ID-TAG-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Personalized Pet ID Tag - Stainless Steel',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 10,
                'supply_price1' => 12.99,
                'supply_price2' => 10.99,
                'supply_price3' => 8.99,
                'unit_cost' => 6.00,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'PET-FIRST-AID-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Pet First Aid Kit - Complete Emergency Kit',
                'supply_qty' => 0,
                'supply_uom' => 'kit',
                'supply_min_qty' => 3,
                'supply_price1' => 34.99,
                'supply_price2' => 29.99,
                'supply_price3' => 24.99,
                'unit_cost' => 18.00,
                'low_stock_threshold_percentage' => 10,
            ],
            [
                'supply_sku' => 'PET-TRAVEL-BOWL-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Collapsible Travel Bowl - Portable Design',
                'supply_qty' => 0,
                'supply_uom' => 'pcs',
                'supply_min_qty' => 8,
                'supply_price1' => 8.99,
                'supply_price2' => 7.99,
                'supply_price3' => 6.99,
                'unit_cost' => 4.00,
                'low_stock_threshold_percentage' => 20,
            ],
            [
                'supply_sku' => 'PET-CLEANING-001',
                'supply_item_class' => 'consumable',
                'supply_description' => 'Pet Stain & Odor Remover - Enzyme Formula (32oz)',
                'supply_qty' => 0,
                'supply_uom' => 'bottle',
                'supply_min_qty' => 5,
                'supply_price1' => 16.99,
                'supply_price2' => 14.99,
                'supply_price3' => 12.99,
                'unit_cost' => 8.50,
                'low_stock_threshold_percentage' => 15,
            ],
            [
                'supply_sku' => 'PET-TRAINING-001',
                'supply_item_class' => 'non-consumable',
                'supply_description' => 'Clicker Training Kit - with Treats & Guide',
                'supply_qty' => 0,
                'supply_uom' => 'kit',
                'supply_min_qty' => 5,
                'supply_price1' => 19.99,
                'supply_price2' => 17.99,
                'supply_price3' => 15.99,
                'unit_cost' => 10.00,
                'low_stock_threshold_percentage' => 15,
            ],
        ];

        // Get the created item types
        $itemTypes = ItemType::whereIn('name', array_column($petItemTypes, 'name'))->get();

        // Create supply profiles with proper relationships
        foreach ($petSupplies as $supply) {
            // Determine appropriate item type based on SKU prefix
            $itemType = null;
            if (str_starts_with($supply['supply_sku'], 'DOG')) {
                $itemType = $itemTypes->where('name', 'Dog Supplies')->first();
            } elseif (str_starts_with($supply['supply_sku'], 'CAT')) {
                $itemType = $itemTypes->where('name', 'Cat Supplies')->first();
            } elseif (str_starts_with($supply['supply_sku'], 'FISH')) {
                $itemType = $itemTypes->where('name', 'Fish Supplies')->first();
            } elseif (str_starts_with($supply['supply_sku'], 'HAMSTER') || str_starts_with($supply['supply_sku'], 'RABBIT') || str_starts_with($supply['supply_sku'], 'GUINEA') || str_starts_with($supply['supply_sku'], 'SMALL-ANIMAL')) {
                $itemType = $itemTypes->where('name', 'Small Animal Supplies')->first();
            } elseif (str_starts_with($supply['supply_sku'], 'REPTILE')) {
                $itemType = $itemTypes->where('name', 'Reptile Supplies')->first();
            } else {
                // Default to Pet Accessories for general items
                $itemType = $itemTypes->where('name', 'Pet Accessories')->first();
            }

            // Create the supply profile
            SupplyProfile::updateOrCreate(
                ['supply_sku' => $supply['supply_sku']],
                array_merge($supply, [
                    'item_type_id' => $itemType ? $itemType->id : $itemTypes->first()->id,
                ])
            );
        }

        $this->command->info('Pet goods shop items seeded successfully!');
    }
} 