<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Allocation Matrix - {{ $batch->ref_no }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 5px;
        }
        .header {
            text-align: left;
            margin-bottom: 5px;
        }
        .header h1 {
            margin: 0 0 5px 0;
            font-size: 20px;
        }
        .header p {
            font-size: 12px;
        }
        table {
            width: auto;
        }
        th, td {
            border: 1px solid #000;
            padding: 2px;
            text-align: left;
            vertical-align: top;
        }
        th {
            font-weight: bold;
            font-size: 12px;
            background-color: #f9f9f9;
        }
        td {
            font-size: 12px;
        }
        .product-header {
            min-width: 120px;
        }
        .quantity-cell {
            text-align: center;
            min-width: 50px;
        }
        .footer {
            margin-top: 5px;
            text-align: left;
            font-size: 10px;
            padding-top: 5px;
        }
        @media print {
            body { margin: 0; }
        }
    </style>
</head>
<body>
    <div class="header">
        <p><strong>Batch Reference:</strong> {{ $batch->ref_no }}<br>
        <strong>Batch Number:</strong> {{ $batch->batch_number }}<br>
        <strong>Generated:</strong> {{ $generated_at->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Branch</th>
                @foreach($products as $product)
                    <th class="product-header">
                        {{ $product->name }}
                        @if($product->color)
                            <br><small>({{ $product->color->name }})</small>
                        @endif
                        <br><small>{{ $product->sku }}</small>
                    </th>
                @endforeach
               {{-- <th class="quantity-cell text-red-700">Total</th> --}}
            </tr>
        </thead>
        <tbody>
            @foreach($branchAllocations as $branchAllocation)
                <tr>
                    <td>
                        <strong>{{ $branchAllocation->branch->name }}</strong>
                    </td>
                    @php
                        $branchTotal = 0;
                    @endphp
                    @foreach($products as $product)
                        @php
                            $item = $branchAllocation->items->where('product_id', $product->id)->first();
                            $quantity = $item ? $item->quantity : 0;
                            $branchTotal += $quantity;
                        @endphp
                        <td class="quantity-cell ">{{ $quantity }}</td>
                    @endforeach
                    {{-- <td class="quantity-cell  text-red-700"><strong>{{ $branchTotal }}</strong></td> --}}
                </tr>
            @endforeach

            <!-- Product Totals Row -->
            <tr>
                {{-- <td><strong>TOTAL</strong></td> --}}
                @php
                    $grandTotal = 0;
                @endphp
                @foreach($products as $product)
                    @php
                        $productTotal = $branchAllocations->sum(function($branchAllocation) use ($product) {
                            $item = $branchAllocation->items->where('product_id', $product->id)->first();
                            return $item ? $item->quantity : 0;
                        });
                        $grandTotal += $productTotal;
                    @endphp
                    {{-- <td class="quantity-cell"><strong>{{ $productTotal }}</strong></td> --}}
                @endforeach
                {{-- <td class="quantity-cell  text-red-700"><strong>{{ $grandTotal }}</strong></td> --}}
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Inventory Management System on {{ $generated_at->format('F j, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>