version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: inventory-jovanni-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - app

  app:
    build: .
    image: inventory-jovanni-app
    container_name: inventory-jovanni-app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:wOtTC9tc+PMFkmrGZb4FpoNJ4jDrfoA+iYFkzckOhF0=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory_jovanni
      - DB_USERNAME=jovanni
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: inventory-jovanni-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: inventory_jovanni
      MYSQL_USER: jovanni
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:7-alpine
    container_name: inventory-jovanni-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    volumes:
      - redisdata:/data

  # Reverb service disabled - uncomment if needed
  # reverb:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.reverb
  #   container_name: inventory-jovanni-reverb
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - REVERB_APP_ID=116692
  #     - REVERB_APP_KEY=y6tzoywvblbve39gvsuh
  #     - REVERB_APP_SECRET=geerxqbgevoymkkzmx5f
  #     - REVERB_HOST=0.0.0.0
  #     - REVERB_PORT=8080
  #     - REVERB_SCHEME=http
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=redis
  #   depends_on:
  #     - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: inventory-jovanni-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: jovanni
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    depends_on:
      - db

volumes:
  dbdata:
  redisdata: