<x-slot:header>Purchase Order</x-slot:header>
<x-slot:subheader>Create Purchase Order</x-slot:subheader>

<div class="">
    <div class="">
        {{-- Flash Messages --}}
        @if (session()->has('error'))
            <x-flash-message type="error" :message="session('error')" />
        @endif

        @if (session()->has('success'))
            <x-flash-message type="success" :message="session('success')" />
        @endif

        {{-- Purchase Order Details --}}
        <x-collapsible-card title="Purchase Order Details" open="true" size="full">
            <form wire:submit.prevent="submit">
                <div class="grid gap-6 mb-2 md:grid-cols-2">
                    {{-- PO Number (auto-generated) --}}
                    <x-input
                        type="text"
                        name="po_num_display"
                        label="PO Number"
                        value="<Auto-generated on save>"
                        readonly="true"
                        disabled="true"
                    />

                    {{-- Ordered By --}}
                    <x-input
                        type="text"
                        name="ordered_by"
                        label="Ordered By"
                        wire:model="ordered_by"
                        readonly="true"
                        disabled="true"
                    />

                    {{-- Supplier (searchable) --}}
                    <div class="mb-4"
                        x-data="{
                            open: false,
                            search: '',
                            selectedId: @entangle('supplier_id').live,
                            options: @js($suppliers->map(fn($s) => ['id' => $s->id, 'name' => $s->name])->toArray()),
                            get filtered() {
                                if (!this.search) return this.options;
                                return this.options.filter(o =>
                                    o.name.toLowerCase().includes(this.search.toLowerCase())
                                );
                            },
                            selectedLabel() {
                                const found = this.options.find(o => o.id === this.selectedId);
                                return found ? found.name : '';
                            },
                            select(option) {
                                this.selectedId = option.id;
                                this.search = '';
                                this.open = false;
                                $wire.set('supplier_id', option.id);
                            }
                        }"
                    >
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                            Supplier
                        </label>
                        <div class="relative">
                            <input
                                type="text"
                                x-model="search"
                                @focus="open = true"
                                @click.away="open = false"
                                :placeholder="selectedLabel() || 'Search supplier...'"
                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            />
                            <div class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                                <svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                                </svg>
                            </div>

                            <div
                                x-show="open"
                                x-transition
                                class="absolute z-20 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-60 overflow-y-auto dark:bg-gray-800 dark:border-gray-700"
                            >
                                <template x-if="filtered.length === 0">
                                    <div class="px-3 py-2 text-sm text-gray-500 dark:text-gray-400">
                                        No suppliers found
                                    </div>
                                </template>
                                <template x-for="option in filtered" :key="option.id">
                                    <button
                                        type="button"
                                        class="w-full text-left px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-700 flex items-center justify-between"
                                        @click="select(option)"
                                    >
                                        <span x-text="option.name" class="text-gray-900 dark:text-white"></span>
                                        <span
                                            x-show="option.id === selectedId"
                                            class="text-xs text-blue-600 dark:text-blue-400"
                                        >
                                            Selected
                                        </span>
                                    </button>
                                </template>
                            </div>
                        </div>
                        @error('supplier_id')
                            <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Currency (from supplier) --}}
                    @if($selectedCurrency)
                        <x-input
                            type="text"
                            name="currency_display"
                            label="Currency"
                            :value="$selectedCurrency->name . ' (' . $selectedCurrency->symbol . ')'"
                            readonly="true"
                            disabled="true"
                        />
                    @endif

                    {{-- Receiving Department --}}
                    <x-dropdown
                        wire:model="deliver_to"
                        name="deliver_to"
                        label="Receiving Department"
                        :options="$departments->pluck('name', 'id')->toArray()"
                        placeholder="Select department"
                        required="true"
                    />

                    {{-- Order Date --}}
                    <x-input
                        type="date"
                        name="order_date"
                        label="Order Date"
                        wire:model="order_date"
                        required="true"
                    />

                    {{-- Expected Delivery Date --}}
                    <x-input
                        type="date"
                        name="expected_delivery_date"
                        label="Expected Delivery Date"
                        wire:model="expected_delivery_date"
                    />
                </div>
            </form>
        </x-collapsible-card>

        {{-- Products List & Items Section --}}
        <x-collapsible-card title="List of Items to Order" open="true" size="full">
            <div class="flex items-center justify-between p-4 pr-10">
                <div class="flex space-x-6">
                    <!-- Title handled by x-collapsible-card -->
                </div>
                <div class="flex space-x-3 items-center">
                    <x-button
                        type="button"
                        variant="primary"
                        size="md"
                        wire:click="openModal"
                    >
                        <svg class="w-3.5 h-3.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 18 18">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M9 1v16M1 9h16" />
                        </svg>
                        Add Item
                    </x-button>
                </div>
            </div>

            {{-- Add Item Modal --}}
            <x-modal wire:model="showModal" class="max-w-4xl max-h-[90vh]">
                {{-- Header --}}
                <div class="flex items-start justify-between mb-4">
                    <div>
                        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                            Add Item to Purchase Order
                        </h3>
                        <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">
                            Search existing products or add new product by supplier code (creates placeholder if needed)
                        </p>
                    </div>
                    <button
                        type="button"
                        wire:click="closeModal"
                        class="ml-3 inline-flex items-center rounded-full p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-500 dark:hover:text-gray-300 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                    >
                        <span class="sr-only">Close</span>
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                        </svg>
                    </button>
                </div>

                {{-- Tabs: Search | Add new Product --}}
                <div class="flex border-b border-gray-200 dark:border-gray-600 mb-4">
                    <button
                        type="button"
                        wire:click="$set('addMode', 'search')"
                        class="px-4 py-2 text-sm font-medium rounded-t-lg {{ $addMode === 'search' ? 'bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 border-b-2 border-blue-500' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300' }}"
                    >
                        Search existing product
                    </button>
                    <button
                        type="button"
                        wire:click="$set('addMode', 'supplier_code')"
                        class="px-4 py-2 text-sm font-medium rounded-t-lg {{ $addMode === 'supplier_code' ? 'bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 border-b-2 border-blue-500' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300' }}"
                    >
                        Add new Product
                    </button>
                </div>

                @if($addMode === 'supplier_code')
                    {{-- Add new Product form --}}
                    <div class="space-y-4">
                        <div>
                            <label for="addBySupplierCode" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Supplier Code</label>
                            <input
                                type="text"
                                id="addBySupplierCode"
                                wire:model.live="addBySupplierCode"
                                placeholder="Enter supplier code (e.g. ABC-123)"
                                class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400"
                            />
                            @error('addBySupplierCode') <p class="mt-1 text-sm text-red-600 dark:text-red-500">{{ $message }}</p> @enderror
                        </div>
                        <div>
                            <label for="addNewProductColor" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Color Code</label>
                            <div class="relative" x-data x-on:click.outside="$wire.set('addNewProductColorDropdown', false)" x-on:keydown.escape.window="$wire.set('addNewProductColorDropdown', false)">
                                <div class="relative">
                                    <div class="pointer-events-none absolute inset-y-0 left-0 pl-3 flex items-center">
                                        <svg aria-hidden="true" class="h-5 w-5 text-gray-400 dark:text-gray-500" fill="currentColor" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                        </svg>
                                    </div>
                                    <input
                                        type="text"
                                        id="addNewProductColor"
                                        wire:model.live.debounce.300ms="addNewProductColorSearch"
                                        wire:focus="$set('addNewProductColorDropdown', true)"
                                        placeholder="Search by color code or name…"
                                        autocomplete="off"
                                        aria-label="Search and select color"
                                        class="block w-full min-h-[38px] h-10 pl-10 pr-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-sm text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                    />
                                    @if($addNewProductColorDropdown)
                                        <div class="absolute z-30 mt-2 w-full max-h-48 overflow-auto rounded-lg border border-gray-200 dark:border-gray-600 bg-white dark:bg-gray-800 shadow-lg py-1">
                                            @forelse($this->filteredCreateColors as $color)
                                                <button
                                                    type="button"
                                                    wire:click="selectCreateColor({{ $color->id }})"
                                                    class="flex w-full items-center gap-2 px-3 py-2 text-left text-sm hover:bg-gray-50 dark:hover:bg-gray-700 {{ $addNewProductColorId == $color->id ? 'bg-indigo-50 dark:bg-indigo-900/30' : 'text-gray-900 dark:text-white' }}"
                                                >
                                                    <span class="flex-1 min-w-0 font-medium truncate">{{ $color->code }}{{ $color->name ? ' - ' . $color->name : '' }}</span>
                                                    @if($addNewProductColorId == $color->id)
                                                        <svg class="h-4 w-4 text-indigo-500 shrink-0" viewBox="0 0 20 20" fill="none">
                                                            <path d="M5 11.5L8.5 15L15 5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" />
                                                        </svg>
                                                    @endif
                                                </button>
                                            @empty
                                                <div class="px-3 py-3 text-xs text-gray-500 dark:text-gray-400">
                                                    No colors match your search.
                                                </div>
                                            @endforelse
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="grid gap-4 md:grid-cols-3">
                            <div>
                                <label for="supplier_code_unit_price" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Unit Price ({{ $selectedCurrency?->symbol ?? '₱' }})</label>
                                <input
                                    type="number"
                                    id="supplier_code_unit_price"
                                    wire:model.live="unit_price"
                                    step="0.01"
                                    min="0"
                                    class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                                />
                                @error('unit_price') <p class="mt-1 text-sm text-red-600 dark:text-red-500">{{ $message }}</p> @enderror
                            </div>
                            <div>
                                <label for="addNewProductSellingPrice" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Selling Price (₱)</label>
                                <input
                                    type="number"
                                    id="addNewProductSellingPrice"
                                    wire:model.live="addNewProductSellingPrice"
                                    step="0.01"
                                    min="0"
                                    placeholder="Optional"
                                    class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400"
                                />
                                @error('addNewProductSellingPrice') <p class="mt-1 text-sm text-red-600 dark:text-red-500">{{ $message }}</p> @enderror
                            </div>
                            <div>
                                <label for="supplier_code_order_qty" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Order Quantity</label>
                                <input
                                    type="number"
                                    id="supplier_code_order_qty"
                                    wire:model.live="order_qty"
                                    step="0.01"
                                    min="0.01"
                                    class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                                />
                                @error('order_qty') <p class="mt-1 text-sm text-red-600 dark:text-red-500">{{ $message }}</p> @enderror
                            </div>
                        </div>
                    </div>
                @else
                {{-- Search and Filters --}}
                <div class="grid gap-4 mb-4 md:grid-cols-2">
                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Search Product</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                        stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                                </svg>
                            </div>
                            <input
                                type="text"
                                wire:model.live.debounce.300ms="search"
                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder="Search by name, SKU, Product ID, or Supplier Code..."
                            />
                        </div>
                    </div>
                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category</label>
                        <select
                            wire:model.live="categoryFilter"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 pr-10 appearance-none dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                        >
                            <option value="">All Categories</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                {{-- Product List --}}
                <div class="border border-gray-200 rounded-lg dark:border-gray-600 overflow-hidden">
                    <div class="max-h-64 overflow-y-auto">
                        @forelse($products as $product)
                            <div
                                wire:click="selectProduct({{ $product->id }})"
                                class="p-4 hover:bg-blue-50 dark:hover:bg-blue-900/30 cursor-pointer border-b border-gray-200 dark:border-gray-600 last:border-b-0 {{ $selected_product == $product->id ? 'bg-blue-50 dark:bg-blue-900/50 border-l-4 border-blue-500' : '' }}"
                            >
                                <div class="flex justify-between items-start">
                                    <div class="flex-1 space-y-1.5">
                                        <div class="font-medium text-gray-900 dark:text-white">
                                            {{ $product->remarks ?? $product->name }}
                                            @if ($product->color)
                                                <span class="text-gray-500 dark:text-gray-400">
                                                    · {{ $product->color->name ?? $product->color->code }}
                                                </span>
                                            @endif
                                        </div>
                                        <div class="text-sm font-mono text-gray-600 dark:text-gray-400">
                                            ID: {{ $product->product_number ?? '—' }}
                                        </div>
                                        <div class="text-sm font-mono text-gray-600 dark:text-gray-400">
                                            SKU: {{ $product->sku ?? '—' }}
                                        </div>
                                        <div class="text-sm text-gray-600 dark:text-gray-400">
                                            Supplier Code: {{ $product->supplier_code ?? '—' }}
                                        </div>
                                        @if ($product->category)
                                            <div class="text-xs text-gray-500 dark:text-gray-400">
                                                {{ $product->category->name }}
                                            </div>
                                        @endif
                                    </div>
                                    <div class="text-right ml-4 flex-shrink-0">
                                        <div class="text-xs text-gray-500 dark:text-gray-400 mb-1">Cost</div>
                                        <div class="font-semibold text-gray-900 dark:text-white">
                                            ₱{{ number_format($product->cost, 2) }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <div class="p-6 text-center text-gray-500 dark:text-gray-400">
                                <svg class="w-12 h-12 mx-auto mb-2 text-gray-400 dark:text-gray-500" fill="none"
                                    stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"></path>
                                </svg>
                                <p>No products found</p>
                            </div>
                        @endforelse
                    </div>
                </div>
                <div class="mt-3">
                    {{ $products->links() }}
                </div>

                {{-- Quantity and Price Inputs (search mode) --}}
                @if($selected_product)
                    <div class="mt-4 border-t border-gray-200 dark:border-gray-600 pt-4">
                        <div class="mb-3 text-sm text-gray-700 dark:text-gray-300">
                            <span class="font-medium">Selected product:</span>
                            <span class="ml-1">
                                {{-- Display basic identifier info from the currently selected row --}}
                                {{ optional($products->firstWhere('id', $selected_product))->remarks
                                    ?? optional($products->firstWhere('id', $selected_product))->name }}
                            </span>
                        </div>
                        <div class="grid gap-4 md:grid-cols-2">
                        <x-input
                            type="number"
                            name="unit_price"
                            :label="'Unit Price (' . ($selectedCurrency?->symbol ?? '₱') . ')'"
                            wire:model="unit_price"
                            step="0.01"
                            required="true"
                        />
                        <x-input
                            type="number"
                            name="order_qty"
                            label="Order Quantity"
                            wire:model="order_qty"
                            step="0.01"
                            required="true"
                        />
                        </div>
                    </div>
                @endif
                @endif

                {{-- Modal Footer --}}
                <div class="mt-6 flex items-center justify-end space-x-3">
                    <x-button type="button" variant="secondary" size="md" wire:click="closeModal">
                        Cancel
                    </x-button>
                    @if($addMode === 'supplier_code')
                        <x-button
                            type="button"
                            variant="primary"
                            size="md"
                            wire:click="addItemBySupplierCode"
                            wire:loading.attr="disabled"
                            :disabled="empty(trim($addBySupplierCode ?? '')) || (float)($order_qty ?? 0) < 0.01 || (float)($unit_price ?? -1) < 0"
                        >
                            Add Item
                        </x-button>
                    @else
                        <x-button
                            type="button"
                            variant="primary"
                            size="md"
                            wire:click="addItem"
                            :disabled="!$selected_product"
                        >
                            Add Item
                        </x-button>
                    @endif
                </div>
            </x-modal>

            {{-- Ordered Items Table --}}
            <div class="overflow-x-auto">
                <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                    <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-5 py-3 text-left">Product ID</th>
                            <th scope="col" class="px-5 py-3 text-left">SKU</th>
                            <th scope="col" class="px-5 py-3 text-left">Product Name</th>
                            <th scope="col" class="px-5 py-3 text-left">Supplier Code</th>
                            <th scope="col" class="px-5 py-3 text-right">Unit Price</th>
                            <th scope="col" class="px-5 py-3 text-right">Qty</th>
                            <th scope="col" class="px-5 py-3 text-right">Total</th>
                            <th scope="col" class="px-5 py-3 text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($paginatedOrderedItems as $index => $item)
                            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                                <td class="px-5 py-4">
                                    <div class="text-sm font-mono text-gray-600 dark:text-gray-400">
                                        {{ $item['product_number'] ?? '—' }}
                                    </div>
                                </td>
                                <td class="px-5 py-4">
                                    <div class="text-sm font-mono text-gray-600 dark:text-gray-400">
                                        {{ $item['sku'] ?? '—' }}
                                    </div>
                                </td>
                                <td class="px-5 py-4">
                                    <div class="font-medium text-gray-900 dark:text-white">
                                        {{ $item['name'] ?? 'N/A' }}
                                    </div>
                                    @if(!empty($item['color']))
                                        <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">
                                            {{ $item['color'] }}
                                        </div>
                                    @endif
                                </td>
                                <td class="px-5 py-4">
                                    <div class="text-sm text-gray-600 dark:text-gray-400">
                                        {{ $item['supplier_code'] ?? '—' }}
                                    </div>
                                </td>
                                <td class="px-5 py-4 text-right">
                                    <div class="text-sm text-gray-900 dark:text-white">
                                        {{ $selectedCurrency?->symbol ?? '₱' }}{{ number_format($item['unit_price'] ?? 0, 2) }}
                                    </div>
                                </td>
                                <td class="px-5 py-4 text-right">
                                    <div class="text-sm text-gray-900 dark:text-white">
                                        {{ number_format($item['order_qty'] ?? 0, 2) }} {{ $item['uom'] ?? 'pcs' }}
                                    </div>
                                </td>
                                <td class="px-5 py-4 text-right">
                                    <div class="text-sm font-semibold text-gray-900 dark:text-white">
                                        {{ $selectedCurrency?->symbol ?? '₱' }}{{ number_format($item['total_price'] ?? 0, 2) }}
                                    </div>
                                </td>
                                <td class="px-5 py-4 text-center">
                                    <x-button
                                        type="button"
                                        variant="danger"
                                        size="sm"
                                        wire:click="removeItem({{ count($orderedItems) - 1 - ($index + (($orderedItemsPage - 1) * $orderedItemsPerPage)) }})"
                                    >
                                        Remove
                                    </x-button>
                                </td>
                            </tr>
                        @empty
                            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                                <td colspan="8" class="px-6 py-8 text-center">
                                    <div class="flex flex-col items-center justify-center space-y-4">
                                        <svg class="w-12 h-12 text-gray-400 dark:text-gray-500" fill="none"
                                            stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"></path>
                                        </svg>
                                        <p class="text-lg font-medium text-gray-900 dark:text-white">No Items Added</p>
                                        <p class="text-sm text-gray-500 dark:text-gray-400">
                                            Please add items to your purchase order using the "Add Item" button above.
                                        </p>
                                    </div>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                    @if(!empty($orderedItems))
                        <tfoot class="text-sm font-semibold text-gray-900 bg-gray-100 dark:bg-gray-700 dark:text-white">
                            <tr>
                                <td colspan="5" class="px-5 py-3 text-right">Total:</td>
                                <td class="px-5 py-3 text-right">
                                    {{ number_format($this->totalQuantity, 2) }}
                                </td>
                                <td class="px-5 py-3 text-right">
                                    {{ $selectedCurrency?->symbol ?? '₱' }}{{ number_format($this->totalAmount, 2) }}
                                </td>
                                <td class="px-5 py-3"></td>
                            </tr>
                        </tfoot>
                    @endif
                </table>
            </div>

            {{-- Pagination + Actions --}}
            <div class="py-4 px-3 space-y-4">
                <div class="flex items-center justify-between">
                    <div class="flex items-center space-x-4">
                        <label class="text-sm font-medium text-gray-900 dark:text-white">Per Page:</label>
                        <x-dropdown
                            wire:model.live="orderedItemsPerPage"
                            name="orderedItemsPerPage"
                            :options="[
                                '5' => '5',
                                '10' => '10',
                                '25' => '25',
                                '50' => '50',
                                '100' => '100'
                            ]"
                            placeholder="Select"
                        />
                    </div>
                    @if($orderedItemsTotalPages > 1)
                        <div class="flex items-center space-x-2">
                            <x-button
                                type="button"
                                variant="secondary"
                                size="sm"
                                wire:click="previousOrderedItemsPage"
                                :disabled="$orderedItemsPage <= 1"
                            >
                                Previous
                            </x-button>
                            @for($i = 1; $i <= $orderedItemsTotalPages; $i++)
                                <x-button
                                    type="button"
                                    wire:click="goToOrderedItemsPage({{ $i }})"
                                    :variant="$orderedItemsPage == $i ? 'primary' : 'secondary'"
                                    size="sm"
                                >
                                    {{ $i }}
                                </x-button>
                            @endfor
                            <x-button
                                type="button"
                                variant="secondary"
                                size="sm"
                                wire:click="nextOrderedItemsPage"
                                :disabled="$orderedItemsPage >= $orderedItemsTotalPages"
                            >
                                Next
                            </x-button>
                        </div>
                    @endif
                </div>

                {{-- Totals + Primary Actions --}}
                <div class="flex items-center justify-end space-x-4">
                    <div class="flex items-center space-x-6 mr-auto">
                        @if(!empty($orderedItems))
                            <div class="text-sm text-gray-600 dark:text-gray-400">
                                <span class="font-medium">Total Items:</span> {{ count($orderedItems) }}
                            </div>
                            <div class="text-sm text-gray-600 dark:text-gray-400">
                                <span class="font-medium">Total Quantity:</span> {{ number_format($this->totalQuantity, 2) }}
                            </div>
                            <div class="text-lg font-bold text-gray-900 dark:text-white">
                                <span class="font-medium">Grand Total:</span> {{ $selectedCurrency?->symbol ?? '₱' }}{{ number_format($this->totalAmount, 2) }}
                            </div>
                        @endif
                    </div>

                    <x-button
                        type="button"
                        variant="secondary"
                        size="md"
                        href="{{ route('pomanagement.purchaseorder') }}"
                    >
                        Cancel
                    </x-button>

                    <x-button
                        type="button"
                        variant="primary"
                        size="md"
                        wire:click="submit"
                        :disabled="empty($orderedItems)"
                    >
                        Submit Purchase Order
                    </x-button>
                </div>
            </div>
        </x-collapsible-card>
    </div>
</div>